# -*- coding: utf-8 -*-
"""Task_1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UYH5GWe3r9r5IWAHT7_BgQ95RwSH_MX4
"""

inp = open("/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 04/input 1a.txt","r")
out= open("/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 04/output 1a.txt", "w")
N, M= inp.readline().split()
N,M= int(N), int(M)
arr=[[int(0) for i in range(N+1)] for j in range(N+1)]

for i in range(M):
    temp=inp.readline().split()
    arr[int(temp[0])][int(temp[1])]=int(temp[2])
for j in arr:
    out.write(f'{j}\n')
inp.close()
out.close()

#Take a 2D array using list comprehension and then store the weight accordingly in the array.