# -*- coding: utf-8 -*-
"""task_2b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iyLSigYJr8M-0EXL7AOUxUvg5O71ofjz
"""

inp=open('/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 02/input 2b.txt', 'r')
out=open('/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 02/output 2b.txt', 'w')

N = int(inp.readline())
arr1=inp.readline().split()

M = int(inp.readline())
arr2 = inp.readline().split()

i=0
j=0
k=0
new_arr=[0]*(N+M)

while i<len(arr1) and j<len(arr2):
        if int(arr1[i]) < int(arr2[j]):
            new_arr[k] = int(arr1[i])
            i+=1
            k+=1

        else:
             new_arr[k] = int(arr2[j])
             j+=1
             k+=1

while i<len(arr1):
    new_arr[k] = int(arr1[i])
    i+=1
    k+=1

while j<len(arr2):
    new_arr[k] = int(arr2[j])
    j+=1
    k+=1
out.write(f'{new_arr}')


inp.close()
out.close()

"""
Create a new empty array. Then using a loop check the first element of array-1 is greater or less than
the first element of array-2 and goes on. From the comparison first store the greater one to the
new array. After that again check if there are any elements left over in both of the arrays. If yes, then
add them to the new array again using loop.
"""