# -*- coding: utf-8 -*-
"""task_2a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iyLSigYJr8M-0EXL7AOUxUvg5O71ofjz
"""

inp=open('/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 02/input 2a.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 02/output 2a.txt','w')
N = inp.readline()
arr1 = inp.readline().split()

M = inp.readline()
arr2 = inp.readline().split()

arr = arr1 + arr2
arr.sort()
out.write(f'{arr}')

inp.close()
out.close()

# Marge 2 array and then use the build-in sort() function
# as the time complexity of build-in sort() function is O(nlogn).