# -*- coding: utf-8 -*-
"""Task_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GllCwx-7Pspq-DcTeJZEaDbYXOJ9b_4j
"""

inp = open("/content/drive/MyDrive/CSE221 Lab(Spring 24)/Lab 01/input 4.txt", "r")
out = open("/content/drive/MyDrive/CSE221 Lab(Spring 24)/Lab 01/output 4.txt", "w")
N = int(inp.readline())

train = [info.split() for info in inp.readlines()]
name = [train[i][0] for i in range(N)]
place = [train[i][4] for i in range(N)]
time = [train[i][6] for i in range(N)]

for i in range(N):
    idx=i
    for j in range(i+1,N):
        if name[j]<name[idx]:
            idx=j
    name[i], name[idx] = name[idx], name[i]
    place[i], place[idx] = place[idx], place[i]
    time[i], time[idx] = time[idx], time[i]

dic={}
for k in range(N):
    if name[k] in dic:
        dic[name[k]][0].append(time[k])
        dic[name[k]][1].append(place[k])
    else:
        dic[name[k]] = [[time[k]],[place[k]]]

for val in dic.values():
    for m in range(len(val[0])):
        idx = m
        for n in range(m+1,len(val[0])):
            if val[0][n] > val[0][idx]:
                idx=n
        val[0][m], val[0][idx] = val[0][idx], val[0][m]
        val[1][m], val[1][idx] = val[1][idx], val[1][m]

for key, values in dic.items():
    for value in range(len(values[0])) :
        out.write(f'{key} will departure for {values[1][value]} at {values[0][value]}\n')


inp.close()
out.close()

#Firstly, using selection sort, sort the name of the trains in the lexicographicsl order.
#Then make a dictionary where the keys are the sorted train names and values are 2 different list of departure times and place.
#Again, using selection sort, sort the keys of the dictionary.
#Lastly, print the output using dictionary iteration.