# -*- coding: utf-8 -*-
"""Task_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UYH5GWe3r9r5IWAHT7_BgQ95RwSH_MX4
"""

inp = open("/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 07/input 3.txt", "r")
out = open("/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 07/output 3.txt", "w")
N = int(inp.readline())
fs = [0] * (N+1)

def find_ways(N):
    if N == 1:
        return 1
    else:
        fs[1] = 1
        fs[2] = 2

        for i in range(3,len(fs)):
            fs[i] = fs[i-1] + fs[i-2]
        out.write(f"{fs[N]}")
find_ways(N)
inp.close()
out.close()

#Here, the fibonacci concept is used but the result is stored in a veriable so that it doesn't need to be calculated again.