# -*- coding: utf-8 -*-
"""Task_1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UYH5GWe3r9r5IWAHT7_BgQ95RwSH_MX4
"""

from queue import Queue
q = Queue()

inp = open('/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 05/input 1b.txt','r')
out = open('/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 05/output 1b.txt','w')
N, M = inp.readline().split()
N, M = int(N),int(M)
G = [[] for i in range(N+1)]
indegree = [0] * (N + 1)

for a in range(M):
    u,v=inp.readline().split()
    u, v = int(u), int(v)
    G[u].append(v)
    indegree[v]+=1


col=['White']*(N+1)
res = []
cycle = False


def TopologicalSort_BFS(G):
    for i in range(1, N + 1):
        if indegree[i] == 0:
            q.put(i)
    while not q.empty():
        u = q.get()
        res.append(u)
        for v in G[u]:
            indegree[v] -= 1
            if indegree[v] == 0:
                q.put(v)

TopologicalSort_BFS(G)

for i in range(1, N + 1):
        if indegree[i] != 0:
            out.write('IMPOSSIBLE')
            break
else:
    for i in res:
        out.write(f'{i} ')
inp.close()
out.close()

'''
First, we store the occurrence of the indegree of every vertex. Then using
BFS algo, find out vertices where indegree = 0 and delete that vertices and their adjacent edges.
After finishig the BFS if their is any non-zero indegree exist, then the graph cointains a cycle and can't br topologically sorted.
'''