# -*- coding: utf-8 -*-
"""Task_1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UYH5GWe3r9r5IWAHT7_BgQ95RwSH_MX4
"""

inp = open("/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 04/input 1b.txt","r")
out= open("/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 04/output 1b.txt", "w")
N, M= inp.readline().split()
N,M= int(N), int(M)

arr=[[0 for i in range(N+1)] for j in range(N+1)]

for i in range(M):
    temp=inp.readline().split()
    a=int(temp[0])
    b=int(temp[1])
    c=int(temp[2])
    arr[a][b]=(b,c)

for i in range(N+1):
    res = str(i) + ": "
    for j in arr[i]:
        if j !=0:
            res+=f'{j }'
    out.write(f"{res}\n")


inp.close()
out.close()

"""
Take a 2D array using list comprehension, store the neighbor node and weight as a tuple in the
array, and print it accordingly.
"""