# -*- coding: utf-8 -*-
"""task_1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iyLSigYJr8M-0EXL7AOUxUvg5O71ofjz
"""

inp = open("/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 02/input 1a.txt", "r")
out = open("/content/drive/MyDrive/CSE221 Lab(Sp-24)/Lab 02/output 1a.txt", "w")
temp = inp.readline().split()
N, S =int(temp[0]) , int(temp[1])
num = inp.readline().split()
flag = False

for i in range(N):
    for j in range(i+1, N):
        sum = int(num[i]) + int(num[j])
        if sum == S:
          out.write(f"{i+1} {j+1}")
          flag = True

    if flag == True:
        break

if flag==False:
    out.write("IMPOSSIBLE")

inp.close()
out.close()


"""
First declare a flag to check whether any pair exists or not. If not then print ‘Impossible’. To
implement the code we need two loops. First one iterates from the 0th index of the list and inside
the loop it iterates from i+1 index to the end of the list and checks if the sum of the values of
outer loop and inner loop is equal to the input sum. If yes, then print the index of the values and
break.
"""