# -*- coding: utf-8 -*-
"""Task_1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GllCwx-7Pspq-DcTeJZEaDbYXOJ9b_4j
"""

inp = open("/content/drive/MyDrive/CSE221 Lab(Spring 24)/Lab 01/input 1b.txt","r")
out = open("/content/drive/MyDrive/CSE221 Lab(Spring 24)/Lab 01/output 1b.txt", "w")
T = int(inp.readline())
for i in range(T):
    temp = inp.readline()[10:]
    for j in range(len(temp)):
        if temp[j] == '+' or temp[j] == '-' or temp[j] == '*' or temp[j] == '/':
            operator = temp[j]
            n1, n2 = temp.split(operator)

            if operator=='+':
                   out.write(f'The result of {n1}{operator}{n2} is {int(n1) + int(n2)}\n')
            elif operator=='-':
                   out.write(f'The result of {n1}{operator}{n2} is {int(n1) - int(n2)}\n')
            elif operator=='*':
                   out.write(f'The result of {n1}{operator}{n2} is {int(n1) * int(n2)}\n')
            elif operator=='/':
                   out.write(f'The result of {n1}{operator}{n2} is {int(n1) / int(n2)}\n')

inp.close()
out.close()


#Slice the lines to get the numerical part only and from that get the operators.
#Using the operators split the values and then calculate the results and print.